name: GitHub Actions
on: [push]
jobs:
  dev-deploy:
    if: github.ref == 'refs/heads/grecaptcha'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: dev
    steps:
      - run: echo "🎉 ${{ github.repository }}, ${{ github.ref }}, ${{ github.event_name }} , ${{ runner.os }}, "
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: CREDENTIAL_SERVICE=https://credential-service.starks.network ZKID_SERVICE=https://zkid-service.starks.network yarn build
      - uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.KEY }}
          source: ${{ github.workspace }}/packages/app/build
          target: "/home/ubuntu/zkID-interface-v2"
          strip_components: 5
          rm: true
  prod-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: master
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: CREDENTIAL_SERVICE=https://credential-service.zkid.app ZKID_SERVICE=https://zkid-service.zkid.app yarn build
      - uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.KEY }}
          source: ${{ github.workspace }}/packages/app/build
          target: "/home/ubuntu/zkID-interface-v2"
          strip_components: 5
          rm: true
